
parameters:
  python: ''
  sourcepath: ''
  buildoutput: ''


jobs:
- job: BuildExe
  displayName: Build .exe from source
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UsePythonVersion@0
    displayName: "Use Python ${{ parameters.python }}"
    inputs:
      versionSpec: ${{ parameters.python }}
      addToPath: true

  - script: |
      echo Setting up build environment...
      python -m pip install --upgrade pip
      python -m pip install pyinstaller
    displayName: 'Install PyInstaller'

  - script: |
      echo Building the executable...
      pyinstaller --onefile ${{ parameters.sourcepath}} --distpath ${{ parameters.buildoutput}}
    displayName: 'Build .exe'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifacts'
    inputs:
      pathToPublish: "${{ parameters.buildoutput}}"
      artifactName: 'exeArtifact'
